const sidebars = {
  tutorialSidebar: [
    'intro/what-is-eyeflow',
    'intro/why-eyeflow',
    'intro/vs-openclaw',
    'for-end-users/quickstart',
    'for-end-users/first-task',
    'for-end-users/first-rule',
    'for-end-users/ui-dashboard',
    'for-end-users/cli-basics',
    'for-developers/architecture',
    'for-developers/api-reference',
    'for-developers/sdks',
    'for-developers/deployment',
    'for-developers/connectors/overview',
    'for-developers/connectors/slack',
    'for-developers/connectors/postgresql',
    'for-developers/connectors/custom',
    'for-decision-makers/roi-analysis',
    'for-decision-makers/use-cases',
    'for-decision-makers/compliance-security',
    'for-decision-makers/scaling-performance',
    'for-decision-makers/technology-selection',
    'technical-deep-dive/semantic-compilation',
    'technical-deep-dive/llm-ir',
    'technical-deep-dive/svm-runtime',
    'technical-deep-dive/capability-catalog',
    'technical-deep-dive/determinism-guarantees',
    'technical-deep-dive/edge-computing',
    'technical-deep-dive/security-sandbox',
    'technical-deep-dive/performance-benchmarking',
  ],
};

module.exports = sidebars;
