/**
 * SlackDriver — handles 'slack' connector type.
 * query       → list recent messages in a channel
 * executeAction → post message / post block kit message
 */

import { ExecutorContext } from '../../executors/executor.interface';
import { BaseConnectorDriver } from '../connector-driver.interface';
import { ConnectorPayload, ConnectorQueryOptions, ConnectorActionDescriptor } from '../connector-payload.interface';
import { ConnectorDataNormalizer } from '../connector-data-normalizer';

export class SlackDriver extends BaseConnectorDriver {
  canHandle(t: string): boolean { return t === 'slack'; }

  async query(opts: ConnectorQueryOptions, cfg: Record<string, unknown>, ctx: ExecutorContext): Promise<ConnectorPayload> {
    const token = (cfg['token'] ?? cfg['botToken'] ?? ctx.secrets?.['SLACK_TOKEN']) as string;
    const channel = (opts.resource ?? cfg['defaultChannel']) as string;
    const res = await this._api('conversations.history', { channel, limit: opts.limit ?? 20 }, token);
    return ConnectorDataNormalizer.wrap(res, {
      connectorId: this._connectorId(cfg, ctx),
      connectorType: 'slack',
      operation: 'listMessages',
      source: `slack:#${channel}`,
    });
  }

  async executeAction(action: ConnectorActionDescriptor, cfg: Record<string, unknown>, ctx: ExecutorContext): Promise<ConnectorPayload> {
    const token = (cfg['token'] ?? cfg['botToken'] ?? ctx.secrets?.['SLACK_TOKEN']) as string;
    const p = action.params as Record<string, unknown>;

    let method: string;
    let body: Record<string, unknown>;

    const op = action.functionId.replace(/^slack_/, '');
    switch (op) {
      case 'postMessage':
      case 'sendMessage':
      case 'send_message':
      case 'connector_call':  // generic label generated by LLM
      case 'call':
      case 'send':
        method = 'chat.postMessage';
        body = {
          channel: (p['channel'] as string) ?? (cfg['defaultChannel'] as string),
          text: p['text'],
          blocks: p['blocks'],
          attachments: p['attachments'],
          thread_ts: p['threadTs'],
        };
        break;
      case 'updateMessage':
        method = 'chat.update';
        body = { channel: p['channel'], ts: p['ts'], text: p['text'], blocks: p['blocks'] };
        break;
      case 'deleteMessage':
        method = 'chat.delete';
        body = { channel: p['channel'], ts: p['ts'] };
        break;
      default:
        method = op.includes('.') ? op : `chat.${op}`;
        body = { ...(p as Record<string, unknown>) };
    }

    const raw = await this._api(method, body, token);
    return ConnectorDataNormalizer.wrap(raw, {
      connectorId: this._connectorId(cfg, ctx),
      connectorType: 'slack',
      operation: action.functionId,
    });
  }

  private async _api(method: string, body: Record<string, unknown>, token: string): Promise<unknown> {
    const res = await fetch(`https://slack.com/api/${method}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json; charset=utf-8', Authorization: `Bearer ${token}` },
      body: JSON.stringify(body),
    });
    const data = await res.json() as Record<string, unknown>;
    if (!data['ok']) throw new Error(`Slack API error: ${data['error']}`);
    return data;
  }
}
