import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  CreateDateColumn,
  UpdateDateColumn,
  DeleteDateColumn,
  Index,
} from 'typeorm';
import { ApiProperty } from '@nestjs/swagger';

// ── Enums ─────────────────────────────────────────────────────────────────────

export enum WatchPromptMode {
  /** User writes the prompt manually */
  MANUAL   = 'manual',
  /** AI auto-generates the analysis prompt from connector metadata */
  AI_AUTO  = 'ai_auto',
}

export enum WatchRunStatus {
  IDLE     = 'idle',
  RUNNING  = 'running',
  OK       = 'ok',
  ERROR    = 'error',
}

// ── Entity ────────────────────────────────────────────────────────────────────

/**
 * SuggestionWatchEntity
 *
 * Represents a scheduled "watch rule" that periodically fetches context from
 * one or more connectors and runs an LLM analysis to generate suggestions.
 *
 * Key design decisions:
 * - `intervalMinutes` + `jitterPercent` → actual delay = intervalMinutes × (1 ± rnd×jitter/100)
 *   This avoids thundering-herd when many watches share the same nominal interval.
 * - `promptMode = ai_auto` → on each run the system prompt is
 *   regenerated by a meta-LLM call that introspects the connector schema + fresh data.
 * - `promptMode = manual`  → the stored `prompt` is used verbatim as the user-turn content.
 */
@Entity('suggestion_watches')
@Index(['userId', 'enabled'])
@Index(['userId', 'deletedAt'])
export class SuggestionWatchEntity {
  @ApiProperty({ format: 'uuid' })
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  @ApiProperty({ format: 'uuid' })
  @Column({ type: 'uuid' })
  userId!: string;

  // ── Identity ──────────────────────────────────────────────────────────────

  @ApiProperty({ example: 'Monitor MQTT broker health' })
  @Column({ type: 'varchar', length: 255 })
  name!: string;

  @ApiProperty({ nullable: true })
  @Column({ type: 'text', nullable: true })
  description?: string;

  // ── Data sources ──────────────────────────────────────────────────────────

  /** UUIDs of ConnectorEntity rows to analyse */
  @ApiProperty({ type: [String], description: 'Connector IDs to watch' })
  @Column({ type: 'text', array: true, default: '{}' })
  connectorIds!: string[];

  // ── Prompt ────────────────────────────────────────────────────────────────

  @ApiProperty({ enum: WatchPromptMode, default: WatchPromptMode.MANUAL })
  @Column({ type: 'enum', enum: WatchPromptMode, default: WatchPromptMode.MANUAL })
  promptMode!: WatchPromptMode;

  /**
   * The analysis prompt sent as the *user* turn to the LLM.
   * When promptMode = ai_auto this is auto-generated / refreshed.
   * When promptMode = manual the user stores their custom prompt here.
   *
   * Example:
   *   "Analyse les données de ce capteur MQTT et dis-moi les 3 meilleures
   *    actions correctives à effectuer dans les 10 prochaines minutes."
   */
  @ApiProperty()
  @Column({ type: 'text', default: '' })
  prompt!: string;

  /** Optional system-prompt override (replaces the global default) */
  @ApiProperty({ nullable: true })
  @Column({ type: 'text', nullable: true })
  systemPrompt?: string;

  // ── Scheduling ────────────────────────────────────────────────────────────

  /** Nominal interval between automatic runs, in minutes */
  @ApiProperty({ default: 30 })
  @Column({ type: 'float', default: 30 })
  intervalMinutes!: number;

  /**
   * Adds ± randomness to the actual delay to prevent synchronized runs.
   * E.g. jitter=20 with interval=30 → actual delay = 30 × (1 ± rand(0..0.2)) minutes.
   * Set to 0 to disable jitter.
   */
  @ApiProperty({ default: 20, description: '% jitter on interval (0–50)' })
  @Column({ type: 'float', default: 20 })
  jitterPercent!: number;

  @ApiProperty({ default: true })
  @Column({ type: 'boolean', default: true })
  enabled!: boolean;

  // ── Analysis tuning ───────────────────────────────────────────────────────

  @ApiProperty({ default: 5 })
  @Column({ type: 'int', default: 5 })
  maxSuggestionsPerRun!: number;

  @ApiProperty({ default: 50, description: 'Min confidence 0-100' })
  @Column({ type: 'int', default: 50 })
  minConfidence!: number;

  // ── Runtime state ─────────────────────────────────────────────────────────

  @ApiProperty({ enum: WatchRunStatus, default: WatchRunStatus.IDLE })
  @Column({ type: 'enum', enum: WatchRunStatus, default: WatchRunStatus.IDLE })
  lastRunStatus!: WatchRunStatus;

  @ApiProperty({ nullable: true })
  @Column({ type: 'timestamptz', nullable: true })
  lastRunAt?: Date;

  @ApiProperty({ nullable: true })
  @Column({ type: 'timestamptz', nullable: true })
  nextRunAt?: Date;

  @ApiProperty({ default: 0 })
  @Column({ type: 'int', default: 0 })
  lastRunSuggestionsCreated!: number;

  @ApiProperty({ default: 0 })
  @Column({ type: 'int', default: 0 })
  totalRuns!: number;

  @ApiProperty({ nullable: true, description: 'Last error message' })
  @Column({ type: 'text', nullable: true })
  lastError?: string;

  // ── Ownership ─────────────────────────────────────────────────────────────

  @ApiProperty({ format: 'uuid', nullable: true })
  @Column({ type: 'uuid', nullable: true })
  createdBy?: string;

  // ── Timestamps ────────────────────────────────────────────────────────────

  @ApiProperty()
  @CreateDateColumn({ type: 'timestamptz' })
  createdAt!: Date;

  @ApiProperty()
  @UpdateDateColumn({ type: 'timestamptz' })
  updatedAt!: Date;

  @ApiProperty({ nullable: true })
  @DeleteDateColumn({ type: 'timestamptz', nullable: true })
  deletedAt?: Date;
}
