/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "EyeFlow — Semantic Compiler Platform",
  "tagline": "Le LLM comme compilateur statique. Automatisation déterministe, certifiable, ultra-rapide.",
  "favicon": "img/favicon.ico",
  "url": "https://docs.eyeflow.sh",
  "baseUrl": "/",
  "organizationName": "eyeflow-ai",
  "projectName": "eyeflow-docs",
  "trailingSlash": false,
  "onBrokenLinks": "warn",
  "onBrokenMarkdownLinks": "warn",
  "i18n": {
    "defaultLocale": "fr",
    "locales": [
      "fr"
    ],
    "localeConfigs": {
      "fr": {
        "htmlLang": "fr-FR",
        "label": "Français",
        "direction": "ltr"
      }
    },
    "path": "i18n"
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "/home/paul/codes/smart_eneo_server-main/eyeflow/sidebars.js",
          "editUrl": "https://github.com/eyeflow-ai/eyeflow-docs/edit/main/",
          "showLastUpdateTime": true,
          "breadcrumbs": true
        },
        "blog": false,
        "theme": {
          "customCss": "/home/paul/codes/smart_eneo_server-main/eyeflow/src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "announcementBar": {
      "id": "scp_v1",
      "content": "🚀 <strong>EyeFlow SCP v1.0</strong> — Le premier compilateur sémantique certifiable pour systèmes critiques. &nbsp;<a href=\"/docs/intro/what-is-eyeflow\"><strong>Découvrir →</strong></a>",
      "backgroundColor": "#0a0f2e",
      "textColor": "#93c5fd",
      "isCloseable": true
    },
    "colorMode": {
      "defaultMode": "dark",
      "disableSwitch": false,
      "respectPrefersColorScheme": true
    },
    "image": "img/eyeflow-og.png",
    "navbar": {
      "title": "EyeFlow",
      "logo": {
        "alt": "EyeFlow",
        "src": "img/logo.svg"
      },
      "style": "dark",
      "items": [
        {
          "type": "dropdown",
          "label": "📖 Démarrer",
          "position": "left",
          "items": [
            {
              "label": "Qu'est-ce qu'EyeFlow ?",
              "to": "/docs/intro/what-is-eyeflow"
            },
            {
              "label": "Pourquoi EyeFlow ?",
              "to": "/docs/intro/why-eyeflow"
            },
            {
              "label": "vs. Alternatives",
              "to": "/docs/intro/vs-alternatives"
            },
            {
              "label": "Quickstart — 5 min",
              "to": "/docs/getting-started/quickstart"
            },
            {
              "label": "Premier workflow",
              "to": "/docs/getting-started/first-workflow"
            },
            {
              "label": "Dashboard",
              "to": "/docs/getting-started/dashboard"
            }
          ]
        },
        {
          "type": "dropdown",
          "label": "🧠 Comment ça marche",
          "position": "left",
          "items": [
            {
              "label": "Compilation sémantique",
              "to": "/docs/concepts/semantic-compilation"
            },
            {
              "label": "Format LLM-IR",
              "to": "/docs/concepts/llm-ir"
            },
            {
              "label": "Catalogue de capacités",
              "to": "/docs/concepts/capability-catalog"
            },
            {
              "label": "SVM — Machine virtuelle",
              "to": "/docs/concepts/svm-runtime"
            },
            {
              "label": "Sources d'événements",
              "to": "/docs/concepts/event-sources"
            },
            {
              "label": "Exécution distribuée",
              "to": "/docs/concepts/distributed-execution"
            },
            {
              "label": "Contrôle physique",
              "to": "/docs/concepts/physical-control"
            },
            {
              "label": "Appels LLM avancés",
              "to": "/docs/concepts/llm-calls"
            },
            {
              "label": "Audit & Observabilité",
              "to": "/docs/concepts/audit-observability"
            },
            {
              "label": "Sécurité & Certifs",
              "to": "/docs/concepts/security"
            }
          ]
        },
        {
          "type": "dropdown",
          "label": "🏭 Secteurs",
          "position": "left",
          "items": [
            {
              "label": "🏥 Médical & Santé",
              "to": "/docs/verticals/medical"
            },
            {
              "label": "⚙️ Industrie 4.0",
              "to": "/docs/verticals/industrial"
            },
            {
              "label": "🌾 Agriculture de précision",
              "to": "/docs/verticals/agriculture"
            },
            {
              "label": "💰 Finance & Banque",
              "to": "/docs/verticals/finance"
            },
            {
              "label": "📡 IoT & Smart Building",
              "to": "/docs/verticals/iot"
            }
          ]
        },
        {
          "type": "dropdown",
          "label": "👨‍💻 Développeurs",
          "position": "left",
          "items": [
            {
              "label": "Architecture technique",
              "to": "/docs/for-developers/architecture"
            },
            {
              "label": "Référence API REST",
              "to": "/docs/for-developers/api-reference"
            },
            {
              "label": "Déploiement",
              "to": "/docs/for-developers/deployment"
            },
            {
              "label": "Connecteurs",
              "to": "/docs/for-developers/connectors/overview"
            },
            {
              "label": "SDK & Intégration",
              "to": "/docs/for-developers/sdks"
            }
          ]
        },
        {
          "label": "🗺️ Roadmap",
          "to": "/docs/roadmap/implementation",
          "position": "left"
        },
        {
          "type": "localeDropdown",
          "position": "right",
          "dropdownItemsBefore": [],
          "dropdownItemsAfter": []
        },
        {
          "href": "https://github.com/eyeflow-ai",
          "position": "right",
          "className": "header-github-link",
          "aria-label": "GitHub"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Plateforme",
          "items": [
            {
              "label": "Qu'est-ce qu'EyeFlow ?",
              "to": "/docs/intro/what-is-eyeflow"
            },
            {
              "label": "Quickstart",
              "to": "/docs/getting-started/quickstart"
            },
            {
              "label": "Architecture",
              "to": "/docs/for-developers/architecture"
            },
            {
              "label": "API Reference",
              "to": "/docs/for-developers/api-reference"
            }
          ]
        },
        {
          "title": "Concepts clés",
          "items": [
            {
              "label": "Compilation sémantique",
              "to": "/docs/concepts/semantic-compilation"
            },
            {
              "label": "Format LLM-IR",
              "to": "/docs/concepts/llm-ir"
            },
            {
              "label": "SVM Runtime (Rust)",
              "to": "/docs/concepts/svm-runtime"
            },
            {
              "label": "Sécurité & Certifs",
              "to": "/docs/concepts/security"
            }
          ]
        },
        {
          "title": "Secteurs",
          "items": [
            {
              "label": "Médical",
              "to": "/docs/verticals/medical"
            },
            {
              "label": "Industrie",
              "to": "/docs/verticals/industrial"
            },
            {
              "label": "Agriculture",
              "to": "/docs/verticals/agriculture"
            },
            {
              "label": "Finance",
              "to": "/docs/verticals/finance"
            },
            {
              "label": "IoT",
              "to": "/docs/verticals/iot"
            }
          ]
        },
        {
          "title": "Liens",
          "items": [
            {
              "label": "GitHub",
              "href": "https://github.com/eyeflow-ai"
            },
            {
              "label": "Site web",
              "href": "https://eyeflow.sh"
            },
            {
              "label": "Roadmap",
              "to": "/docs/roadmap/implementation"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2026 EyeFlow AI. Tous droits réservés."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "bash",
        "json",
        "python",
        "typescript",
        "javascript",
        "sql",
        "rust",
        "yaml",
        "toml"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 4
    },
    "docs": {
      "sidebar": {
        "hideable": true,
        "autoCollapseCategories": false
      },
      "versionPersistence": "localStorage"
    },
    "metadata": []
  },
  "baseUrlIssueBanner": true,
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "mermaid": false
  }
};
